#pragma once



enum COLLISION_GROUP { CHARACTER, MONSTER, PROP, NPC, PORTAL, GROUP_END };

enum class KEY_STATE
{
	NONE,
	TAP,
	HOLD,
	AWAY
};

enum class KEY
{
	LEFT_ARROW,
	RIGHT_ARROW,
	UP_ARROW,
	DOWN_ARROW,
	TAB,
	OPEN_SQUARE_BRACKET,
	CLOSE_SQUARE_BRACKET,
	F1, F2, F3, F4, F5, F6, F7, F8, F9,
	INSERT, DEL, HOME, END_KEY, PAGE_UP, PAGE_DOWN,
	NUM_1, NUM_2, NUM_3, NUM_4, NUM_5, NUM_6, NUM_7, NUM_8, NUM_9,
	Q, W, E, R, T, Y, U, I, O, P,
	A, S, D, F, G, H, J, K, L,
	Z, X, C, V, B, N, M,
	ALT, CTRL, SHIFT,
	SPACE, ENTER, ESC,
	LBTN, RBTN,
	TYPE_END
};

enum CHANNELID
{
	SOUND_UI,
	SOUND_VOICE_CHARACTER,
	SOUND_VOICE_MONSTER1,
	SOUND_VOICE_MONSTER2,
	SOUND_VOICE_MONSTER3,
	SOUND_SKILL,
	SOUND_SLASH,
	SOUND_SLASH_HIT,
	SOUND_NORMAL_HIT,
	SOUND_FOOT_CHARACTER,
	SOUND_FOOT_MONSTER,
	SOUND_BGM,
	SOUND_SHAKE,
	SOUND_JUMP,
	SOUND_BOSS,
	MAXCHANNEL
};


enum DIMK { DIMK_LBUTTON, DIMK_RBUTTON, DIMK_WHEEL, DIMK_X, DIMK_END };
enum DIMM { DIMM_X, DIMM_Y, DIMM_WHEEL, DIMM_END };